# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

1.19.2


In [6]:
print(np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Jwala Baburaj/.conda/envs/Machine_Learning\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Jwala Baburaj/.conda/envs/Machine_Learning\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Jwala Baburaj/.conda/envs/Machine_Learning\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Jwala Baburaj/.conda/envs/Machine_Learning\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Jwala Baburaj/.conda/envs/Machine_Learning\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Jwala Baburaj/.conda/envs/Machine_Learning\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Jwala Baburaj/.conda/envs/Machine_Learning\\Library\\l

#### 3. Create a null vector of size 10 (★☆☆)

In [30]:
null_vector = np.zeros(10)
null_vector[:] = np.nan
print(null_vector)

[nan nan nan nan nan nan nan nan nan nan]


#### 4.  How to find the memory size of any array (★☆☆)

In [11]:
x = null_vector.size
print(x)

y = null_vector.itemsize
print(y)

memory_size = x * y
print(memory_size)

10
8
80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [20]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [27]:
x = np.zeros(10) # or #np.empty(10) 
x[:] = np.nan
x[4] = 1

print(x)

[nan nan nan nan  1. nan nan nan nan nan]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [31]:
np.arange(10,50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [32]:
np.flip(np.arange(10,50))  #.flip(array) to reverse

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [34]:
#or

np.arange(10,50)[::-1]  #[::-1] to reverse

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [39]:
arr = np.arange(9)

arr = arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [40]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [41]:
np.eye(3)  #numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
#or

np.identity(3) #numpy.identity(n, dtype=None)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [54]:
np.random.random((3,3,3))

array([[[0.92232425, 0.00302129, 0.55655245],
        [0.69464835, 0.98152524, 0.28485825],
        [0.72218477, 0.48230347, 0.54753512]],

       [[0.69435421, 0.50900078, 0.52392227],
        [0.97888667, 0.53398145, 0.49487183],
        [0.53151718, 0.43980465, 0.20653826]],

       [[0.1799137 , 0.17312331, 0.45198667],
        [0.67177979, 0.65949301, 0.27024294],
        [0.3560427 , 0.11926715, 0.4022079 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [63]:
arr = np.random.random((10,10))
print("Original Array:")
print(arr) 

print()
arr_min, arr_max = arr.min(), arr.max()
print("Minimum and Maximum Values:")
print(arr_min, arr_max, sep = ' ')

Original Array:
[[0.12593236 0.67363635 0.65467973 0.16795673 0.18011203 0.66265611
  0.21781196 0.44525178 0.63299399 0.71911078]
 [0.21825646 0.87507385 0.01121453 0.09310023 0.05629158 0.05335766
  0.84691754 0.91058709 0.39099417 0.4873321 ]
 [0.03551518 0.28944437 0.06990997 0.81214071 0.46919517 0.49633718
  0.26369996 0.54024689 0.61660293 0.4362228 ]
 [0.96406727 0.65634035 0.12368546 0.14047481 0.04953229 0.10608483
  0.9916619  0.9442717  0.23670576 0.4826689 ]
 [0.76774585 0.59593277 0.98235936 0.56459219 0.9175042  0.57540629
  0.6727189  0.92723911 0.32559924 0.22267916]
 [0.26254658 0.93416941 0.66796853 0.18916375 0.94440116 0.61690687
  0.75994059 0.91834483 0.86997263 0.92640727]
 [0.10973315 0.71932298 0.04951384 0.83611807 0.33733119 0.66680338
  0.79657117 0.46262346 0.67177538 0.51680321]
 [0.33943241 0.31307575 0.83044546 0.59191369 0.82712368 0.20958365
  0.78755901 0.97139431 0.84139231 0.10788086]
 [0.01929834 0.6442049  0.90377881 0.20741105 0.85056896 0.30390

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [65]:
x = np.random.random(30)
x.mean()

0.46017025228281216

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [79]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
#or #using np.pad()

x = np.zeros((3,3))  #since .pad is used and pad_width = 1 given below, to get a 5x5 matrix start with 3x3

x = np.pad(x, pad_width = 1, constant_values = 1) #numpy.pad(array, pad_width, mode='constant', **kwargs)
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [97]:
x = np.zeros((5,5))

x[1:-1,1:-1] = 1
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [99]:
#or

x = np.ones((3,3))

x = np.pad(x, pad_width = 1, constant_values = 0)
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [100]:
0 * np.nan

nan

In [101]:
np.nan == np.nan

# unknown values cannot be equal to each other

False

In [102]:
#np.inf - floating point representation of (positive) infinity

#np.nan - floating point representation of Not a Number (NaN)

np.inf > np.nan

#if something is not a number, it can't be compared with anything that IS a number and thus, any comparison returns false

False

In [103]:
np.nan - np.nan

nan

In [104]:
np.nan in set([np.nan])

True

In [105]:
0.3 == 3 * 0.1

#Python can’t accurately hold decimals as floats, as in binary 1/10 turns into a repeating decimal, 
#so it rounds to a good amount of decimal places that is fine for normal use.
#It works just like the repeating decimal 1/3, which infinitely repeats.

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [117]:
np.diag([1,2,3,4],k= -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [150]:
x = np.zeros((8,8), dtype = int)


x[1::2,::2] = 1  #(1,0),(1,2)...

x[::2,1::2] = 1  #(0,1),(0,3)...
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [139]:
#numpy.unravel_index(indices, shape, order='C')
#Converts a flat index or array of flat indices into a tuple of coordinate arrays.

print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [149]:
#numpy.tile(A, reps)

y = np.tile([[0,1],[1,0]], (4,4))
y

#[[0,1],
# [1,0]]
# (4,4) repeats the above matrix(2 arrays) 4 times along the rows and columns respectively

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [169]:
x = np.random.random((5,5))
print(x)


normalized_matrix = (x-x.mean())/x.std()
normalized_matrix


[[0.13199745 0.09603614 0.76379192 0.74336618 0.51024012]
 [0.47150721 0.76118694 0.92789484 0.22760949 0.24531149]
 [0.51440204 0.6407497  0.11933725 0.64776017 0.20881686]
 [0.01367317 0.71402879 0.30185882 0.82121206 0.17825831]
 [0.3438525  0.4733708  0.11575545 0.39942303 0.2758045 ]]


array([[-1.12230088, -1.25962804,  1.29036302,  1.21236228,  0.3221126 ],
       [ 0.17420136,  1.28041526,  1.91703073, -0.7571826 , -0.68958309],
       [ 0.33800592,  0.82049578, -1.17064697,  0.84726698, -0.82894691],
       [-1.57415149,  1.10033015, -0.47364312,  1.50963606, -0.9456423 ],
       [-0.3132798 ,  0.18131795, -1.18432498, -0.10106995, -0.57313797]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [172]:
color = np.dtype([("R", np.ubyte, 1), 
                  ("G", np.ubyte, 1),
                  ("B", np.ubyte, 1),
                  ("A", np.ubyte, 1)])
print(color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


<ipython-input-172-82e7d3dde3f3>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("R", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [173]:
x = np.arange(15).reshape((5, 3))
y = np.arange(6).reshape((3, 2))
np.dot(x, y)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [175]:
#or

x = np.dot(np.ones((5, 3)), np.ones((3, 2)))
x

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [183]:
x = np.arange(11)
x[(x > 3) & (x < 8)] *= -1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [191]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)